### ISSUE TITLE
Graceful skip of unpublished packages

### ISSUE THREAD

**Issue by ad-m** [maxzheng/bumper#2]
Hello,

I believe full stop of update if meet unpublished packages is a bit too strongly. I suggest provide warning instead and leave it unchanged.

Greetings,

```
$ bump
[INFO] Checking django-redis-cache
[ERROR] No published version found for django-redis-cache
```

**Comment by maxzheng** [comment]
It is supposed to do that but didn't due to a bug. Try out 0.1.11

Also I didn't get that error when I was testing, so likely you don't have access to https://pypi.python.org/pypi/django-redis-cache/json (that's where bump gets its version info).  You can run with --debug to get details on any failure.
